name: testCI

on:
  workflow_dispatch:
    inputs:
      targetTag:
        required: false
        description: "Input tag here"
        default: ""

env:
  TARGET_BRANCH_NAME: develop
  SUBMODULE_DIR: themes/techblog
  NEW_BRANCH_BASE: design/

jobs:
  checkEnvironment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.env.TARGET_BRANCH_NAME }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - id: stepCLT
        name: Check the Latest Tag
        run: |
          cd "${SUBMODULE_DIR}"
          LATEST_TAG="$(git tag -l --sort -refname | head -n 1)"
          echo "::set-output name=latestTag::$LATEST_TAG"
      - name: Download a Current Tag Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: currentTag
          path: currentTag.json
      - id: stepSCTE
        name: Set the Current Tag to Environment
        if: ${{ success() }}
        run: |
          CURRENT_TAG="$(cat currentTag.json | jq '.version | @sh')"
          echo "::set-output name=currentTag::$CURRENT_TAG"
      - name: Set the Target Tag to Environment
        if: ${{ always() }}
        run: |
          if [ ${{ github.event.inputs.tag }} != '' ]; then
            echo "::set-output name=targetTag::${{ github.event.inputs.tag }}"
          elif [ ${{ steps.stepSCTE.outputs.currentTag }} != '' ]; then
            echo "::set-output name=targetTag::${{ steps.stepSCTE.outputs.currentTag }}"
          else
            exit 1
          fi
  createPR:
    needs: checkEnvironment
    runs-on: ubuntu-latest
    steps:
      - name: Create a New Branch
        run: |
          git switch -c "${NEW_BRANCH_BASE}${TARGET_SUBMODULE_TAG}"
          git push -u origin "${NEW_BRANCH_BASE}${TARGET_SUBMODULE_TAG}"
      - name: Checkout submodule
        run: |
          cd "${SUBMODULE_DIR}"
          git checkout refs/tags/$TARGET_SUBMODULE_TAG
      - name: Add and Commit .gitmodules
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: .gitmodules
          author_name: devel-mckee1531
          author_email: devel.mckee.1531@gmail.com
          message: "The new submodule version is released."
          github_token: ${{ secrets.GITHUB_TOKEN }}
           
