name: testCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: move to submodule directory
        run: cd themes/techblog

      - name: pull
        run: git pull
        
      - name: check latest tag
        run: git tag -l --sort -refname | head -n 1
