name: testCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      tag:
        required: true
        default: "Input tag here"

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: check latest tag
        run: |
          cd themes/techblog
          LATEST_TAG="$(git tag -l --sort -refname | head -n 1)"
          echo "$LATEST_TAG"

      - name: checkout submodule
        run: |
          cd themes/techblog
          git checkout refs/tags/${{ github.event.inputs.tag }}
          
