name: testCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: check latest tag
        run: |
          cd themes/techblog
          git fetch
          git tag -l --sort -refname | head -n 1
          git -v
