name: testCI

on:
  workflow_dispatch:
    inputs:
      targetTag:
        type: string
        required: false
        description: 'Input tag here'
        default: ''

env:
  TARGET_BRANCH_NAME: develop
  SUBMODULE_DIR: themes/techblog
  NEW_BRANCH_BASE: design/
  COMMIT_MESSAGE: 'Update submodule by Github Actions'
  PR_TITLE: 'New Submodule Version is Released'
  PR_BODY: ''

jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Environments
        run: |
          git --version
          gh version
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.env.TARGET_BRANCH_NAME }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: Check Target Tag Validation
        if: ${{ github.event.inputs.targetTag }}
        run: |
          cd "${SUBMODULE_DIR}"
          git tag -l --sort -authordate | grep -x "${{ github.event.inputs.targetTag }}"
          if [ "$?" eq 0 ]; then
            exit 0
          else
            exit 1
          fi

      - id: stepLatestTag
        if: ${{ ! github.event.inputs.targetTag }}
        name: Set the Latest Submodule Tag to Environment
        run: |
          cd "${SUBMODULE_DIR}"
          LATEST_TAG="$(git tag -l --sort -authordate | head -n 1)"
          echo "::set-output name=latestTag::$LATEST_TAG"

      - name: Download a Current Tag Artifact
        if: ${{ ! github.event.inputs.targetTag }}
        uses: actions/download-artifact@v3.0.0
        with:
          name: currentTag
          path: .artifact/currentTag.json

      - id: stepCurrentTag
        name: Set the Current Tag to Environment
        if: ${{ success() }}
        run: |
          CURRENT_TAG="$(cat currentTag.json | jq '.version | @sh')"
          echo "::set-output name=currentTag::$CURRENT_TAG"

      - name: Detect Submodule Updates
        if: ${{ success() }}
        run: |
          if [ ${{ steps.stepLatestTag.outputs.latestTag }} > ${{ steps.stepCurrentTag.outputs.currentTag }} ]; then
            exit 0
          else
            exit 1
          fi
